#!/bin/bash
#
# create .orig.tar.gz for context-modules package
#

if [ "$1" = "-p" ] ; then
  tlnetloc=/home/norbert/public_html/tlpretest/archive
else
  tlnetloc=/home/norbert/public_html/tlnet/archive
fi

package=context-modules
vers=`date +'%Y%m%d'`
basedir=${package}-$vers
if [ -r $basedir ] ; then
  echo $basedir exists, exiting.
  exit 1
fi
mkdir $basedir
for i in `cat debian/included-ctx-modules`; do
  if [ -r $tlnetloc/$i.tar.xz ] ; then
    echo $i.tar.xz
    tar -C $basedir -xf $tlnetloc/$i.tar.xz
  else
    echo "WARNING: missing $tlnetloc/$i.tar.xz!"
  fi
  if [ -r $tlnetloc/$i.source.tar.xz ] ; then
    echo $i.source.tar.xz
    tar -C $basedir -xf $tlnetloc/$i.source.tar.xz
  fi
  if [ -r $tlnetloc/$i.doc.tar.xz ] ; then
    echo $i.doc.tar.xz
    tar -C $basedir -xf $tlnetloc/$i.doc.tar.xz
  fi
done
if [ -r ${package}_$vers.orig.tar.gz ] ; then
  echo "${package}_$vers.orig.tar.gz present, not creating new one"
  echo "be aware that there might be conflicts between packaged versions"
  exit 1
fi
tar -czf ${package}_$vers.orig.tar.gz $basedir


